// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt-BR'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * A​r​t​e​s
		 */
		arts: string
		/**
		 * S​o​b​r​e
		 */
		about: string
	}
	footer: {
		copy: {
			/**
			 * C​o​p​i​a​r​ ​e​m​a​i​l
			 */
			tooltip: string
			/**
			 * E​m​a​i​l​ ​c​o​p​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
			 */
			success: string
		}
		/**
		 * c​o​n​t​a​t​o
		 */
		contact: string
		/**
		 * s​e​g​u​i​r
		 */
		follow: string
		/**
		 * l​i​n​k​s
		 */
		links: string
		/**
		 * i​d​i​o​m​a​s
		 */
		languages: string
		/**
		 * D​e​s​e​n​v​o​l​v​i​d​o​ ​p​o​r
		 */
		dev: string
	}
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * Artes
		 */
		arts: () => LocalizedString
		/**
		 * Sobre
		 */
		about: () => LocalizedString
	}
	footer: {
		copy: {
			/**
			 * Copiar email
			 */
			tooltip: () => LocalizedString
			/**
			 * Email copiado com sucesso!
			 */
			success: () => LocalizedString
		}
		/**
		 * contato
		 */
		contact: () => LocalizedString
		/**
		 * seguir
		 */
		follow: () => LocalizedString
		/**
		 * links
		 */
		links: () => LocalizedString
		/**
		 * idiomas
		 */
		languages: () => LocalizedString
		/**
		 * Desenvolvido por
		 */
		dev: () => LocalizedString
	}
}

export type Formatters = {}
