// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt-BR'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	copy: {
		/**
		 * c​o​p​i​a​r
		 */
		tooltip: string
		/**
		 * C​o​p​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o​!
		 */
		success: string
	}
	footer: {
		/**
		 * c​o​n​t​a​t​o
		 */
		contact: string
		/**
		 * s​e​g​u​i​r
		 */
		follow: string
		/**
		 * l​i​n​k​s
		 */
		links: string
		/**
		 * i​d​i​o​m​a​s
		 */
		languages: string
		/**
		 * D​e​s​e​n​v​o​l​v​i​d​o​ ​p​o​r
		 */
		dev: string
	}
}

export type TranslationFunctions = {
	copy: {
		/**
		 * copiar
		 */
		tooltip: () => LocalizedString
		/**
		 * Copiado com sucesso!
		 */
		success: () => LocalizedString
	}
	footer: {
		/**
		 * contato
		 */
		contact: () => LocalizedString
		/**
		 * seguir
		 */
		follow: () => LocalizedString
		/**
		 * links
		 */
		links: () => LocalizedString
		/**
		 * idiomas
		 */
		languages: () => LocalizedString
		/**
		 * Desenvolvido por
		 */
		dev: () => LocalizedString
	}
}

export type Formatters = {}
